version: '3.3'

# this is an alternate proxy setup using haproxy

services:

  proxy:
    image: vfarcic/docker-flow-proxy
    ports:
      - '80:80'
      - '443:443'
      # high public port for healthchecks from external LB
      # ping url: /v1/docker-flow-proxy/ping
      - '9433:8080'
    networks:
      - proxy
    environment:
      LISTENER_ADDRESS: "swarm-listener"
      MODE: "swarm"
      DEBUG: "true"
        # secrets:
            # - cert-docker-dev
    deploy:
      mode: global
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/v1/docker-flow-proxy/ping"]

  swarm-listener:
    image: vfarcic/docker-flow-swarm-listener
    networks:
      - proxy
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    environment:
      - >-
          DF_NOTIFY_CREATE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/reconfigure
      - >-
          DF_NOTIFY_REMOVE_SERVICE_URL=http://proxy:8080/v1/docker-flow-proxy/remove
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  proxy:
    external: true
# secrets:
    # cert-docker-dev:
        # file: ./nginx/dev-full.pem
